[package]
name = "snowtime-render"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
bench = []

[dependencies]
deno_core = "0.405"
deno_error = "0.7"
deno_web = "0.283"
deno_webidl = "0.252"
deno_fetch = "0.276"
deno_net = "0.244"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "time", "macros"] }
anyhow = "1"
libc = "0.2"

[build-dependencies]
deno_core = "0.405"
deno_web = "0.283"
deno_webidl = "0.252"
deno_fetch = "0.276"
deno_net = "0.244"
tokio = { version = "1", features = ["rt", "time"] }
