[package]
name = "snowtime-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
form_urlencoded.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
snowtime-auth.workspace = true
snowtime-core.workspace = true
tokio.workspace = true
