[package]
name = "snowtime-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "snowtime-axum"
path = "src/main.rs"

[dependencies]
axum.workspace = true
base64.workspace = true
libc = "0.2"
rand.workspace = true
snowtime-render = { path = "../render" }
snowtime-server.workspace = true
tokio.workspace = true
tower-http = { version = "0.6", features = ["fs"] }
