import * as v from 'valibot'
import { Description, Uuidv7 } from './common'

export const StartTimerInput = v.object({
  // Generated by the client (uuid v7), so the optimistic entry keeps its key.
  id: Uuidv7,
  description: v.optional(Description, ''),
  projectId: v.nullish(Uuidv7),
})
export type StartTimerInput = v.InferOutput<typeof StartTimerInput>

export const StopTimerInput = v.object({
  // The running entry the client shows; a timer started elsewhere since is left running.
  id: Uuidv7,
})
export type StopTimerInput = v.InferOutput<typeof StopTimerInput>
