import * as v from 'valibot'
import { Entry } from '../entries/entries.schemas'
import { Description, operation, Ticket, Uuidv7 } from '../schemas'

export const StartTimerInput = v.object({
  // Generated by the client (uuid v7), so the optimistic entry keeps its key.
  id: Uuidv7,
  description: v.optional(Description, ''),
  ticket: v.optional(Ticket),
  projectId: v.nullish(Uuidv7),
})
export type StartTimerInput = v.InferOutput<typeof StartTimerInput>

export const StopTimerInput = v.object({
  // The running entry the client shows; a timer started elsewhere since is left running.
  id: Uuidv7,
})
export type StopTimerInput = v.InferOutput<typeof StopTimerInput>

// The running entry, with its project for a timer running in another organization, whose
// projects the view hasn't loaded.
export const RunningTimer = v.object({
  ...Entry.entries,
  project: v.nullable(
    v.object({ id: v.string(), name: v.string(), color: v.nullable(v.string()) }),
  ),
})
export type RunningTimer = v.InferOutput<typeof RunningTimer>

// The running timer spans organizations, so stopping and reading it names no organization.
export const timerOperations = {
  getRunningTimer: operation({
    method: 'GET',
    path: '/api/v1/timer',
    scope: 'user',
    input: undefined,
    output: v.nullable(RunningTimer),
  }),
  startTimer: operation({
    method: 'POST',
    path: '/api/v1/organizations/:organizationId/timer/start',
    scope: 'organization',
    input: StartTimerInput,
    output: v.object({ started: Entry, stopped: v.nullable(Entry) }),
  }),
  stopTimer: operation({
    method: 'POST',
    path: '/api/v1/timer/stop',
    scope: 'user',
    input: StopTimerInput,
    output: Entry,
  }),
}
