/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgRouteImport } from './routes/$org'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as OrgIndexRouteImport } from './routes/$org/index'
import { Route as OrgOrganizationRouteImport } from './routes/$org/organization'
import { Route as OrgProjectsRouteImport } from './routes/$org/projects'
import { Route as OrgReportsRouteImport } from './routes/$org/reports'
import { Route as OrgSettingsRouteImport } from './routes/$org/settings'
import { Route as OrgTimerRouteImport } from './routes/$org/timer'
import { Route as InvitationIdRouteImport } from './routes/invitation.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1TimerRouteImport } from './routes/api/v1/timer'
import { Route as ApiV1OrgsOrgIdEntriesRouteImport } from './routes/api/v1/orgs.$orgId.entries'
import { Route as ApiV1OrgsOrgIdProjectsRouteImport } from './routes/api/v1/orgs.$orgId.projects'
import { Route as ApiV1OrgsOrgIdTimerRouteImport } from './routes/api/v1/orgs.$orgId.timer'
import { Route as ApiV1TimerEntryIdStopRouteImport } from './routes/api/v1/timer.$entryId.stop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrganizationRoute = OrgOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProjectsRoute = OrgProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OrgRoute,
} as any)
const OrgReportsRoute = OrgReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgTimerRoute = OrgTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => OrgRoute,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TimerRoute = ApiV1TimerRouteImport.update({
  id: '/api/v1/timer',
  path: '/api/v1/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrgsOrgIdEntriesRoute = ApiV1OrgsOrgIdEntriesRouteImport.update({
  id: '/api/v1/orgs/$orgId/entries',
  path: '/api/v1/orgs/$orgId/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrgsOrgIdProjectsRoute = ApiV1OrgsOrgIdProjectsRouteImport.update({
  id: '/api/v1/orgs/$orgId/projects',
  path: '/api/v1/orgs/$orgId/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrgsOrgIdTimerRoute = ApiV1OrgsOrgIdTimerRouteImport.update({
  id: '/api/v1/orgs/$orgId/timer',
  path: '/api/v1/orgs/$orgId/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TimerEntryIdStopRoute = ApiV1TimerEntryIdStopRouteImport.update({
  id: '/$entryId/stop',
  path: '/$entryId/stop',
  getParentRoute: () => ApiV1TimerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/$org/organization': typeof OrgOrganizationRoute
  '/$org/projects': typeof OrgProjectsRoute
  '/$org/reports': typeof OrgReportsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/timer': typeof OrgTimerRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/$org/': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/timer': typeof ApiV1TimerRouteWithChildren
  '/api/v1/orgs/$orgId/entries': typeof ApiV1OrgsOrgIdEntriesRoute
  '/api/v1/orgs/$orgId/projects': typeof ApiV1OrgsOrgIdProjectsRoute
  '/api/v1/orgs/$orgId/timer': typeof ApiV1OrgsOrgIdTimerRoute
  '/api/v1/timer/$entryId/stop': typeof ApiV1TimerEntryIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/$org/organization': typeof OrgOrganizationRoute
  '/$org/projects': typeof OrgProjectsRoute
  '/$org/reports': typeof OrgReportsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/timer': typeof OrgTimerRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/$org': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/timer': typeof ApiV1TimerRouteWithChildren
  '/api/v1/orgs/$orgId/entries': typeof ApiV1OrgsOrgIdEntriesRoute
  '/api/v1/orgs/$orgId/projects': typeof ApiV1OrgsOrgIdProjectsRoute
  '/api/v1/orgs/$orgId/timer': typeof ApiV1OrgsOrgIdTimerRoute
  '/api/v1/timer/$entryId/stop': typeof ApiV1TimerEntryIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/$org/organization': typeof OrgOrganizationRoute
  '/$org/projects': typeof OrgProjectsRoute
  '/$org/reports': typeof OrgReportsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/timer': typeof OrgTimerRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/$org/': typeof OrgIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/timer': typeof ApiV1TimerRouteWithChildren
  '/api/v1/orgs/$orgId/entries': typeof ApiV1OrgsOrgIdEntriesRoute
  '/api/v1/orgs/$orgId/projects': typeof ApiV1OrgsOrgIdProjectsRoute
  '/api/v1/orgs/$orgId/timer': typeof ApiV1OrgsOrgIdTimerRoute
  '/api/v1/timer/$entryId/stop': typeof ApiV1TimerEntryIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$org'
    | '/create-organization'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/$org/organization'
    | '/$org/projects'
    | '/$org/reports'
    | '/$org/settings'
    | '/$org/timer'
    | '/invitation/$id'
    | '/$org/'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/timer'
    | '/api/v1/orgs/$orgId/entries'
    | '/api/v1/orgs/$orgId/projects'
    | '/api/v1/orgs/$orgId/timer'
    | '/api/v1/timer/$entryId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/$org/organization'
    | '/$org/projects'
    | '/$org/reports'
    | '/$org/settings'
    | '/$org/timer'
    | '/invitation/$id'
    | '/$org'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/timer'
    | '/api/v1/orgs/$orgId/entries'
    | '/api/v1/orgs/$orgId/projects'
    | '/api/v1/orgs/$orgId/timer'
    | '/api/v1/timer/$entryId/stop'
  id:
    | '__root__'
    | '/'
    | '/$org'
    | '/create-organization'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/$org/organization'
    | '/$org/projects'
    | '/$org/reports'
    | '/$org/settings'
    | '/$org/timer'
    | '/invitation/$id'
    | '/$org/'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/timer'
    | '/api/v1/orgs/$orgId/entries'
    | '/api/v1/orgs/$orgId/projects'
    | '/api/v1/orgs/$orgId/timer'
    | '/api/v1/timer/$entryId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  InvitationIdRoute: typeof InvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1TimerRoute: typeof ApiV1TimerRouteWithChildren
  ApiV1OrgsOrgIdEntriesRoute: typeof ApiV1OrgsOrgIdEntriesRoute
  ApiV1OrgsOrgIdProjectsRoute: typeof ApiV1OrgsOrgIdProjectsRoute
  ApiV1OrgsOrgIdTimerRoute: typeof ApiV1OrgsOrgIdTimerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org': {
      id: '/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/': {
      id: '/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/organization': {
      id: '/$org/organization'
      path: '/organization'
      fullPath: '/$org/organization'
      preLoaderRoute: typeof OrgOrganizationRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/projects': {
      id: '/$org/projects'
      path: '/projects'
      fullPath: '/$org/projects'
      preLoaderRoute: typeof OrgProjectsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/reports': {
      id: '/$org/reports'
      path: '/reports'
      fullPath: '/$org/reports'
      preLoaderRoute: typeof OrgReportsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/settings': {
      id: '/$org/settings'
      path: '/settings'
      fullPath: '/$org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/timer': {
      id: '/$org/timer'
      path: '/timer'
      fullPath: '/$org/timer'
      preLoaderRoute: typeof OrgTimerRouteImport
      parentRoute: typeof OrgRoute
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/timer': {
      id: '/api/v1/timer'
      path: '/api/v1/timer'
      fullPath: '/api/v1/timer'
      preLoaderRoute: typeof ApiV1TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orgs/$orgId/entries': {
      id: '/api/v1/orgs/$orgId/entries'
      path: '/api/v1/orgs/$orgId/entries'
      fullPath: '/api/v1/orgs/$orgId/entries'
      preLoaderRoute: typeof ApiV1OrgsOrgIdEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orgs/$orgId/projects': {
      id: '/api/v1/orgs/$orgId/projects'
      path: '/api/v1/orgs/$orgId/projects'
      fullPath: '/api/v1/orgs/$orgId/projects'
      preLoaderRoute: typeof ApiV1OrgsOrgIdProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orgs/$orgId/timer': {
      id: '/api/v1/orgs/$orgId/timer'
      path: '/api/v1/orgs/$orgId/timer'
      fullPath: '/api/v1/orgs/$orgId/timer'
      preLoaderRoute: typeof ApiV1OrgsOrgIdTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/timer/$entryId/stop': {
      id: '/api/v1/timer/$entryId/stop'
      path: '/$entryId/stop'
      fullPath: '/api/v1/timer/$entryId/stop'
      preLoaderRoute: typeof ApiV1TimerEntryIdStopRouteImport
      parentRoute: typeof ApiV1TimerRoute
    }
  }
}

interface OrgRouteChildren {
  OrgOrganizationRoute: typeof OrgOrganizationRoute
  OrgProjectsRoute: typeof OrgProjectsRoute
  OrgReportsRoute: typeof OrgReportsRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgTimerRoute: typeof OrgTimerRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgOrganizationRoute: OrgOrganizationRoute,
  OrgProjectsRoute: OrgProjectsRoute,
  OrgReportsRoute: OrgReportsRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgTimerRoute: OrgTimerRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

interface ApiV1TimerRouteChildren {
  ApiV1TimerEntryIdStopRoute: typeof ApiV1TimerEntryIdStopRoute
}

const ApiV1TimerRouteChildren: ApiV1TimerRouteChildren = {
  ApiV1TimerEntryIdStopRoute: ApiV1TimerEntryIdStopRoute,
}

const ApiV1TimerRouteWithChildren = ApiV1TimerRoute._addFileChildren(
  ApiV1TimerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
  CreateOrganizationRoute: CreateOrganizationRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  InvitationIdRoute: InvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1TimerRoute: ApiV1TimerRouteWithChildren,
  ApiV1OrgsOrgIdEntriesRoute: ApiV1OrgsOrgIdEntriesRoute,
  ApiV1OrgsOrgIdProjectsRoute: ApiV1OrgsOrgIdProjectsRoute,
  ApiV1OrgsOrgIdTimerRoute: ApiV1OrgsOrgIdTimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
